#!/usr/bin/perl

use strict;
use warnings;
use utf8;
use File::Path qw/mkpath/;
use Getopt::Long;
use Pod::Usage;
use Text::Xslate;
use File::ShareDir qw//;
use File::Copy;
use MIME::Base64;
use Encode;
use File::Basename;
use Jasmine;
use Jasmine::Setup::Skelton;
use Data::Dumper;

GetOptions(
    'help' => \my $help,
    'version' => \my $version
) or pod2usage(0);
pod2usage(1) if $help;
&show_version if $version;

&main;

sub show_version {
    require Jasmine;
    print "Perl: $]\n";
    print "Jasmine: $Jasmine::VERSION\n";
    exit(0);
}

sub main {
    my $module = shift @ARGV or pod2usage(0);
    my $skelton = Jasmine::Setup::Skelton->new(module => $module);
    print Dumper $skelton;
    
    my $dist = $skelton->{dist};
    mkdir $dist or die "Cannot mkdir '$dist': $!";
    chdir $dist or die $!;
    $skelton->write_assets;
    # copy customized Kossy
    $skelton->copy_shared_files('extlib');
    $skelton->render_file('app.psgi', 'app.psgi');
    $skelton->render_file('lib/<<PATH>>.pm', 'lib/__PATH__.pm');
    #

    exit(0);
}

=head1 SYNOPSIS

    % jasmine-setup MyApp

=cut

1;
__DATA__
